language: en
pipeline:
  - name: SpacyNLP
    model: External_data/spacy.word2vec.model
  - name: profanity_analyzer.ProfanityAnalyzer # custom model
  - name: SpacyTokenizer
  # SpacyTokenizer is advanced, it also uses rules
  # - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  # - name: CRFEntityExtractor
  # - name: SklearnIntentClassfier
  # DIETClassifer used instead of CRFEntityExtractor and SklearnIntentClassfier and is a transformer
  - name: DIETClassifer
    epochs: 200
    random_seed: 2
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: KerasPolicy
    max_history: 3
    epochs: 60
    random_seed: 5
    validation_split: 0.2
  - name: MappingPolicy
  - name: FallbackPolicy
